//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopForums {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PopForums.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        public static string AccountCreated {
            get {
                return ResourceManager.GetString("AccountCreated", resourceCulture);
            }
        }
        
        public static string AccountReady {
            get {
                return ResourceManager.GetString("AccountReady", resourceCulture);
            }
        }
        
        public static string AccountReadyCheckEmail {
            get {
                return ResourceManager.GetString("AccountReadyCheckEmail", resourceCulture);
            }
        }
        
        public static string AccountVerified {
            get {
                return ResourceManager.GetString("AccountVerified", resourceCulture);
            }
        }
        
        public static string AlreadyCreatedAccount {
            get {
                return ResourceManager.GetString("AlreadyCreatedAccount", resourceCulture);
            }
        }
        
        public static string AsYouWouldLikeItToAppear {
            get {
                return ResourceManager.GetString("AsYouWouldLikeItToAppear", resourceCulture);
            }
        }
        
        public static string AtLeastSixChar {
            get {
                return ResourceManager.GetString("AtLeastSixChar", resourceCulture);
            }
        }
        
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        public static string CreateAccountButton {
            get {
                return ResourceManager.GetString("CreateAccountButton", resourceCulture);
            }
        }
        
        public static string CreateAnAccount {
            get {
                return ResourceManager.GetString("CreateAnAccount", resourceCulture);
            }
        }
        
        public static string EditYourProfile {
            get {
                return ResourceManager.GetString("EditYourProfile", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string EmailProblemAccount {
            get {
                return ResourceManager.GetString("EmailProblemAccount", resourceCulture);
            }
        }
        
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        public static string Forums {
            get {
                return ResourceManager.GetString("Forums", resourceCulture);
            }
        }
        
        public static string HaveReadTOS {
            get {
                return ResourceManager.GetString("HaveReadTOS", resourceCulture);
            }
        }
        
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string MarkAllForumsRead {
            get {
                return ResourceManager.GetString("MarkAllForumsRead", resourceCulture);
            }
        }
        
        public static string MyBirthdayIsOnOrBefore {
            get {
                return ResourceManager.GetString("MyBirthdayIsOnOrBefore", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string NeedToVerifyExistingAccount {
            get {
                return ResourceManager.GetString("NeedToVerifyExistingAccount", resourceCulture);
            }
        }
        
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        public static string PrivateMessages {
            get {
                return ResourceManager.GetString("PrivateMessages", resourceCulture);
            }
        }
        
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        public static string RegisteredUsers {
            get {
                return ResourceManager.GetString("RegisteredUsers", resourceCulture);
            }
        }
        
        public static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string SubscribeToList {
            get {
                return ResourceManager.GetString("SubscribeToList", resourceCulture);
            }
        }
        
        public static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
        
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        public static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        public static string Topics {
            get {
                return ResourceManager.GetString("Topics", resourceCulture);
            }
        }
        
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        public static string TotalPosts {
            get {
                return ResourceManager.GetString("TotalPosts", resourceCulture);
            }
        }
        
        public static string TotalTopics {
            get {
                return ResourceManager.GetString("TotalTopics", resourceCulture);
            }
        }
        
        public static string UseDaylight {
            get {
                return ResourceManager.GetString("UseDaylight", resourceCulture);
            }
        }
        
        public static string UsersOnline {
            get {
                return ResourceManager.GetString("UsersOnline", resourceCulture);
            }
        }
        
        public static string MustBe13 {
            get {
                return ResourceManager.GetString("MustBe13", resourceCulture);
            }
        }
        
        public static string MustAcceptTOS {
            get {
                return ResourceManager.GetString("MustAcceptTOS", resourceCulture);
            }
        }
        
        public static string RetypeYourPassword {
            get {
                return ResourceManager.GetString("RetypeYourPassword", resourceCulture);
            }
        }
        
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        public static string NameInUse {
            get {
                return ResourceManager.GetString("NameInUse", resourceCulture);
            }
        }
        
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        public static string ValidEmailAddressRequired {
            get {
                return ResourceManager.GetString("ValidEmailAddressRequired", resourceCulture);
            }
        }
        
        public static string EmailInUse {
            get {
                return ResourceManager.GetString("EmailInUse", resourceCulture);
            }
        }
        
        public static string EmailBanned {
            get {
                return ResourceManager.GetString("EmailBanned", resourceCulture);
            }
        }
        
        public static string IPBanned {
            get {
                return ResourceManager.GetString("IPBanned", resourceCulture);
            }
        }
        
        public static string RetypePasswordMustMatch {
            get {
                return ResourceManager.GetString("RetypePasswordMustMatch", resourceCulture);
            }
        }
        
        public static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        public static string EnterVerificationCode {
            get {
                return ResourceManager.GetString("EnterVerificationCode", resourceCulture);
            }
        }
        
        public static string ForumHomePage {
            get {
                return ResourceManager.GetString("ForumHomePage", resourceCulture);
            }
        }
        
        public static string MustBeRegisteredToEditAccount {
            get {
                return ResourceManager.GetString("MustBeRegisteredToEditAccount", resourceCulture);
            }
        }
        
        public static string NoUserFoundWithEmail {
            get {
                return ResourceManager.GetString("NoUserFoundWithEmail", resourceCulture);
            }
        }
        
        public static string SendEmailWithNewCodeButton {
            get {
                return ResourceManager.GetString("SendEmailWithNewCodeButton", resourceCulture);
            }
        }
        
        public static string VerificationEmailSent {
            get {
                return ResourceManager.GetString("VerificationEmailSent", resourceCulture);
            }
        }
        
        public static string VerificationFailure {
            get {
                return ResourceManager.GetString("VerificationFailure", resourceCulture);
            }
        }
        
        public static string VerificationIfYouNeed {
            get {
                return ResourceManager.GetString("VerificationIfYouNeed", resourceCulture);
            }
        }
        
        public static string VerificationLinkBad {
            get {
                return ResourceManager.GetString("VerificationLinkBad", resourceCulture);
            }
        }
        
        public static string VerifyAccount {
            get {
                return ResourceManager.GetString("VerifyAccount", resourceCulture);
            }
        }
        
        public static string VerifyCodeButton {
            get {
                return ResourceManager.GetString("VerifyCodeButton", resourceCulture);
            }
        }
        
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        public static string AvatarDelete {
            get {
                return ResourceManager.GetString("AvatarDelete", resourceCulture);
            }
        }
        
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        public static string ChangeEmailButton {
            get {
                return ResourceManager.GetString("ChangeEmailButton", resourceCulture);
            }
        }
        
        public static string ChangeEmailConsequence {
            get {
                return ResourceManager.GetString("ChangeEmailConsequence", resourceCulture);
            }
        }
        
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        public static string ChangeYourEmailPassword {
            get {
                return ResourceManager.GetString("ChangeYourEmailPassword", resourceCulture);
            }
        }
        
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        public static string EmailChangeSuccess {
            get {
                return ResourceManager.GetString("EmailChangeSuccess", resourceCulture);
            }
        }
        
        public static string EmailNew {
            get {
                return ResourceManager.GetString("EmailNew", resourceCulture);
            }
        }
        
        public static string EmailNewRetype {
            get {
                return ResourceManager.GetString("EmailNewRetype", resourceCulture);
            }
        }
        
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        public static string EmailsMustMatch {
            get {
                return ResourceManager.GetString("EmailsMustMatch", resourceCulture);
            }
        }
        
        public static string EmailUser {
            get {
                return ResourceManager.GetString("EmailUser", resourceCulture);
            }
        }
        
        public static string ForcePlainTextBox {
            get {
                return ResourceManager.GetString("ForcePlainTextBox", resourceCulture);
            }
        }
        
        public static string ForgotInstructions {
            get {
                return ResourceManager.GetString("ForgotInstructions", resourceCulture);
            }
        }
        
        public static string ForgotInstructionsSent {
            get {
                return ResourceManager.GetString("ForgotInstructionsSent", resourceCulture);
            }
        }
        
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        public static string ForgotPasswordQuestion {
            get {
                return ResourceManager.GetString("ForgotPasswordQuestion", resourceCulture);
            }
        }
        
        public static string HideVanity {
            get {
                return ResourceManager.GetString("HideVanity", resourceCulture);
            }
        }
        
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        public static string Joined {
            get {
                return ResourceManager.GetString("Joined", resourceCulture);
            }
        }
        
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        public static string LoginAlready {
            get {
                return ResourceManager.GetString("LoginAlready", resourceCulture);
            }
        }
        
        public static string LoginBad {
            get {
                return ResourceManager.GetString("LoginBad", resourceCulture);
            }
        }
        
        public static string ManagePhotos {
            get {
                return ResourceManager.GetString("ManagePhotos", resourceCulture);
            }
        }
        
        public static string ManageYourPhotos {
            get {
                return ResourceManager.GetString("ManageYourPhotos", resourceCulture);
            }
        }
        
        public static string NewPasswordSaved {
            get {
                return ResourceManager.GetString("NewPasswordSaved", resourceCulture);
            }
        }
        
        public static string NotRegisteredQuestion {
            get {
                return ResourceManager.GetString("NotRegisteredQuestion", resourceCulture);
            }
        }
        
        public static string OldPasswordIncorrect {
            get {
                return ResourceManager.GetString("OldPasswordIncorrect", resourceCulture);
            }
        }
        
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        public static string PasswordNew {
            get {
                return ResourceManager.GetString("PasswordNew", resourceCulture);
            }
        }
        
        public static string PasswordNewRetype {
            get {
                return ResourceManager.GetString("PasswordNewRetype", resourceCulture);
            }
        }
        
        public static string PasswordOld {
            get {
                return ResourceManager.GetString("PasswordOld", resourceCulture);
            }
        }
        
        public static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        public static string PasswordResetLinkInvalid {
            get {
                return ResourceManager.GetString("PasswordResetLinkInvalid", resourceCulture);
            }
        }
        
        public static string PasswordResetNote {
            get {
                return ResourceManager.GetString("PasswordResetNote", resourceCulture);
            }
        }
        
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        public static string PhotoDelete {
            get {
                return ResourceManager.GetString("PhotoDelete", resourceCulture);
            }
        }
        
        public static string PhotoNotApproved {
            get {
                return ResourceManager.GetString("PhotoNotApproved", resourceCulture);
            }
        }
        
        public static string ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }
        
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        public static string Replies {
            get {
                return ResourceManager.GetString("Replies", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string SendEmailButton {
            get {
                return ResourceManager.GetString("SendEmailButton", resourceCulture);
            }
        }
        
        public static string SendPM {
            get {
                return ResourceManager.GetString("SendPM", resourceCulture);
            }
        }
        
        public static string ShowProfileDetails {
            get {
                return ResourceManager.GetString("ShowProfileDetails", resourceCulture);
            }
        }
        
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        public static string StartedBy {
            get {
                return ResourceManager.GetString("StartedBy", resourceCulture);
            }
        }
        
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        public static string UploadNew {
            get {
                return ResourceManager.GetString("UploadNew", resourceCulture);
            }
        }
        
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        public static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        public static string WebVisit {
            get {
                return ResourceManager.GetString("WebVisit", resourceCulture);
            }
        }
        
        public static string YourIP {
            get {
                return ResourceManager.GetString("YourIP", resourceCulture);
            }
        }
        
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        public static string SendNameEmail {
            get {
                return ResourceManager.GetString("SendNameEmail", resourceCulture);
            }
        }
        
        public static string SendNamePM {
            get {
                return ResourceManager.GetString("SendNamePM", resourceCulture);
            }
        }
        
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        public static string UnsubscribeFail {
            get {
                return ResourceManager.GetString("UnsubscribeFail", resourceCulture);
            }
        }
        
        public static string UnsubscribeLinkBad {
            get {
                return ResourceManager.GetString("UnsubscribeLinkBad", resourceCulture);
            }
        }
        
        public static string UnsubscribeNote {
            get {
                return ResourceManager.GetString("UnsubscribeNote", resourceCulture);
            }
        }
        
        public static string AddForum {
            get {
                return ResourceManager.GetString("AddForum", resourceCulture);
            }
        }
        
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        public static string AllowImages {
            get {
                return ResourceManager.GetString("AllowImages", resourceCulture);
            }
        }
        
        public static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        public static string BanRemove {
            get {
                return ResourceManager.GetString("BanRemove", resourceCulture);
            }
        }
        
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        public static string CategoryEditTitle {
            get {
                return ResourceManager.GetString("CategoryEditTitle", resourceCulture);
            }
        }
        
        public static string CategoryMoveError {
            get {
                return ResourceManager.GetString("CategoryMoveError", resourceCulture);
            }
        }
        
        public static string CensorReplacementChar {
            get {
                return ResourceManager.GetString("CensorReplacementChar", resourceCulture);
            }
        }
        
        public static string CensorWords {
            get {
                return ResourceManager.GetString("CensorWords", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string DeleteAndBanButton {
            get {
                return ResourceManager.GetString("DeleteAndBanButton", resourceCulture);
            }
        }
        
        public static string DeleteUserButton {
            get {
                return ResourceManager.GetString("DeleteUserButton", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string EditForum {
            get {
                return ResourceManager.GetString("EditForum", resourceCulture);
            }
        }
        
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        public static string EmailBan {
            get {
                return ResourceManager.GetString("EmailBan", resourceCulture);
            }
        }
        
        public static string EmailIpBan {
            get {
                return ResourceManager.GetString("EmailIpBan", resourceCulture);
            }
        }
        
        public static string EmailNewOptional {
            get {
                return ResourceManager.GetString("EmailNewOptional", resourceCulture);
            }
        }
        
        public static string EmailUsers {
            get {
                return ResourceManager.GetString("EmailUsers", resourceCulture);
            }
        }
        
        public static string ErrorLog {
            get {
                return ResourceManager.GetString("ErrorLog", resourceCulture);
            }
        }
        
        public static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        public static string ForumAdapter {
            get {
                return ResourceManager.GetString("ForumAdapter", resourceCulture);
            }
        }
        
        public static string ForumHome {
            get {
                return ResourceManager.GetString("ForumHome", resourceCulture);
            }
        }
        
        public static string ForumPermisions {
            get {
                return ResourceManager.GetString("ForumPermisions", resourceCulture);
            }
        }
        
        public static string ForumSettings {
            get {
                return ResourceManager.GetString("ForumSettings", resourceCulture);
            }
        }
        
        public static string ForumsUncat {
            get {
                return ResourceManager.GetString("ForumsUncat", resourceCulture);
            }
        }
        
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        public static string IpBan {
            get {
                return ResourceManager.GetString("IpBan", resourceCulture);
            }
        }
        
        public static string IpHistory {
            get {
                return ResourceManager.GetString("IpHistory", resourceCulture);
            }
        }
        
        public static string IsApproved {
            get {
                return ResourceManager.GetString("IsApproved", resourceCulture);
            }
        }
        
        public static string IsSubscribed {
            get {
                return ResourceManager.GetString("IsSubscribed", resourceCulture);
            }
        }
        
        public static string LogErrors {
            get {
                return ResourceManager.GetString("LogErrors", resourceCulture);
            }
        }
        
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        public static string LogMod {
            get {
                return ResourceManager.GetString("LogMod", resourceCulture);
            }
        }
        
        public static string LogSecurity {
            get {
                return ResourceManager.GetString("LogSecurity", resourceCulture);
            }
        }
        
        public static string MinimumTimeBetweenPosts {
            get {
                return ResourceManager.GetString("MinimumTimeBetweenPosts", resourceCulture);
            }
        }
        
        public static string ModerationLog {
            get {
                return ResourceManager.GetString("ModerationLog", resourceCulture);
            }
        }
        
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        public static string NewUserApprovedWithoutVerification {
            get {
                return ResourceManager.GetString("NewUserApprovedWithoutVerification", resourceCulture);
            }
        }
        
        public static string NewUserImageApprovedWithoutMod {
            get {
                return ResourceManager.GetString("NewUserImageApprovedWithoutMod", resourceCulture);
            }
        }
        
        public static string Parsing {
            get {
                return ResourceManager.GetString("Parsing", resourceCulture);
            }
        }
        
        public static string PasswordNewOptional {
            get {
                return ResourceManager.GetString("PasswordNewOptional", resourceCulture);
            }
        }
        
        public static string PopForumsAdmin {
            get {
                return ResourceManager.GetString("PopForumsAdmin", resourceCulture);
            }
        }
        
        public static string PostsPerPage {
            get {
                return ResourceManager.GetString("PostsPerPage", resourceCulture);
            }
        }
        
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        public static string SecurityLog {
            get {
                return ResourceManager.GetString("SecurityLog", resourceCulture);
            }
        }
        
        public static string ServerTime {
            get {
                return ResourceManager.GetString("ServerTime", resourceCulture);
            }
        }
        
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        public static string SessionLength {
            get {
                return ResourceManager.GetString("SessionLength", resourceCulture);
            }
        }
        
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        public static string SubjectAndBodyNotEmpty {
            get {
                return ResourceManager.GetString("SubjectAndBodyNotEmpty", resourceCulture);
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string TopicsPerPage {
            get {
                return ResourceManager.GetString("TopicsPerPage", resourceCulture);
            }
        }
        
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        public static string UserAvatarMaxDim {
            get {
                return ResourceManager.GetString("UserAvatarMaxDim", resourceCulture);
            }
        }
        
        public static string UserDeleteWarning {
            get {
                return ResourceManager.GetString("UserDeleteWarning", resourceCulture);
            }
        }
        
        public static string UserImageApproval {
            get {
                return ResourceManager.GetString("UserImageApproval", resourceCulture);
            }
        }
        
        public static string UserImageMaxDim {
            get {
                return ResourceManager.GetString("UserImageMaxDim", resourceCulture);
            }
        }
        
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        public static string AddNewForum {
            get {
                return ResourceManager.GetString("AddNewForum", resourceCulture);
            }
        }
        
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        public static string BodyHtml {
            get {
                return ResourceManager.GetString("BodyHtml", resourceCulture);
            }
        }
        
        public static string ClickToLoadMorePosts {
            get {
                return ResourceManager.GetString("ClickToLoadMorePosts", resourceCulture);
            }
        }
        
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        public static string CommentsOptional {
            get {
                return ResourceManager.GetString("CommentsOptional", resourceCulture);
            }
        }
        
        public static string CreateJunkWordButton {
            get {
                return ResourceManager.GetString("CreateJunkWordButton", resourceCulture);
            }
        }
        
        public static string CreateNewReply {
            get {
                return ResourceManager.GetString("CreateNewReply", resourceCulture);
            }
        }
        
        public static string CreateNewRole {
            get {
                return ResourceManager.GetString("CreateNewRole", resourceCulture);
            }
        }
        
        public static string CreateNewTopic {
            get {
                return ResourceManager.GetString("CreateNewTopic", resourceCulture);
            }
        }
        
        public static string DeleteAllErrors {
            get {
                return ResourceManager.GetString("DeleteAllErrors", resourceCulture);
            }
        }
        
        public static string DeleteJunkWordButton {
            get {
                return ResourceManager.GetString("DeleteJunkWordButton", resourceCulture);
            }
        }
        
        public static string DeleteSelectedRole {
            get {
                return ResourceManager.GetString("DeleteSelectedRole", resourceCulture);
            }
        }
        
        public static string EditPost {
            get {
                return ResourceManager.GetString("EditPost", resourceCulture);
            }
        }
        
        public static string EmailUsersQueued {
            get {
                return ResourceManager.GetString("EmailUsersQueued", resourceCulture);
            }
        }
        
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        public static string EventTime {
            get {
                return ResourceManager.GetString("EventTime", resourceCulture);
            }
        }
        
        public static string FavoriteMustBeLoggedIn {
            get {
                return ResourceManager.GetString("FavoriteMustBeLoggedIn", resourceCulture);
            }
        }
        
        public static string FavoritesDontHave {
            get {
                return ResourceManager.GetString("FavoritesDontHave", resourceCulture);
            }
        }
        
        public static string FavoriteTopics {
            get {
                return ResourceManager.GetString("FavoriteTopics", resourceCulture);
            }
        }
        
        public static string ForumMoveError {
            get {
                return ResourceManager.GetString("ForumMoveError", resourceCulture);
            }
        }
        
        public static string ForumPermissionInstructions {
            get {
                return ResourceManager.GetString("ForumPermissionInstructions", resourceCulture);
            }
        }
        
        public static string FromEmailAddress {
            get {
                return ResourceManager.GetString("FromEmailAddress", resourceCulture);
            }
        }
        
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        public static string IncludeSignature {
            get {
                return ResourceManager.GetString("IncludeSignature", resourceCulture);
            }
        }
        
        public static string IndexingInterval {
            get {
                return ResourceManager.GetString("IndexingInterval", resourceCulture);
            }
        }
        
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        public static string IsRunning {
            get {
                return ResourceManager.GetString("IsRunning", resourceCulture);
            }
        }
        
        public static string JunkWords {
            get {
                return ResourceManager.GetString("JunkWords", resourceCulture);
            }
        }
        
        public static string MarkForumRead {
            get {
                return ResourceManager.GetString("MarkForumRead", resourceCulture);
            }
        }
        
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        public static string Millseconds {
            get {
                return ResourceManager.GetString("Millseconds", resourceCulture);
            }
        }
        
        public static string NamePosts {
            get {
                return ResourceManager.GetString("NamePosts", resourceCulture);
            }
        }
        
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        public static string PermRoles {
            get {
                return ResourceManager.GetString("PermRoles", resourceCulture);
            }
        }
        
        public static string PostID {
            get {
                return ResourceManager.GetString("PostID", resourceCulture);
            }
        }
        
        public static string PostingRoles {
            get {
                return ResourceManager.GetString("PostingRoles", resourceCulture);
            }
        }
        
        public static string PostNewTopic {
            get {
                return ResourceManager.GetString("PostNewTopic", resourceCulture);
            }
        }
        
        public static string PreviewTopic {
            get {
                return ResourceManager.GetString("PreviewTopic", resourceCulture);
            }
        }
        
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        public static string RemoveAll {
            get {
                return ResourceManager.GetString("RemoveAll", resourceCulture);
            }
        }
        
        public static string SendingInterval {
            get {
                return ResourceManager.GetString("SendingInterval", resourceCulture);
            }
        }
        
        public static string SmtpPassword {
            get {
                return ResourceManager.GetString("SmtpPassword", resourceCulture);
            }
        }
        
        public static string SmtpPort {
            get {
                return ResourceManager.GetString("SmtpPort", resourceCulture);
            }
        }
        
        public static string SmtpServer {
            get {
                return ResourceManager.GetString("SmtpServer", resourceCulture);
            }
        }
        
        public static string SmtpUser {
            get {
                return ResourceManager.GetString("SmtpUser", resourceCulture);
            }
        }
        
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        public static string SubmitNewTopic {
            get {
                return ResourceManager.GetString("SubmitNewTopic", resourceCulture);
            }
        }
        
        public static string SubmitReply {
            get {
                return ResourceManager.GetString("SubmitReply", resourceCulture);
            }
        }
        
        public static string TopicID {
            get {
                return ResourceManager.GetString("TopicID", resourceCulture);
            }
        }
        
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        public static string UseEsmtpCred {
            get {
                return ResourceManager.GetString("UseEsmtpCred", resourceCulture);
            }
        }
        
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        public static string UserIDTarget {
            get {
                return ResourceManager.GetString("UserIDTarget", resourceCulture);
            }
        }
        
        public static string UserImageApprovalNotReq {
            get {
                return ResourceManager.GetString("UserImageApprovalNotReq", resourceCulture);
            }
        }
        
        public static string UseSsl {
            get {
                return ResourceManager.GetString("UseSsl", resourceCulture);
            }
        }
        
        public static string ViewingRoles {
            get {
                return ResourceManager.GetString("ViewingRoles", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string CloseOnReply {
            get {
                return ResourceManager.GetString("CloseOnReply", resourceCulture);
            }
        }
        
        public static string FavoriteMake {
            get {
                return ResourceManager.GetString("FavoriteMake", resourceCulture);
            }
        }
        
        public static string FavoriteRemove {
            get {
                return ResourceManager.GetString("FavoriteRemove", resourceCulture);
            }
        }
        
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        public static string Moderator {
            get {
                return ResourceManager.GetString("Moderator", resourceCulture);
            }
        }
        
        public static string NameAvatar {
            get {
                return ResourceManager.GetString("NameAvatar", resourceCulture);
            }
        }
        
        public static string NameLastEdit {
            get {
                return ResourceManager.GetString("NameLastEdit", resourceCulture);
            }
        }
        
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        public static string PostReply {
            get {
                return ResourceManager.GetString("PostReply", resourceCulture);
            }
        }
        
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        public static string RecentTopics {
            get {
                return ResourceManager.GetString("RecentTopics", resourceCulture);
            }
        }
        
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        public static string ShowMorePosts {
            get {
                return ResourceManager.GetString("ShowMorePosts", resourceCulture);
            }
        }
        
        public static string ShowPreviousPosts {
            get {
                return ResourceManager.GetString("ShowPreviousPosts", resourceCulture);
            }
        }
        
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        public static string Undelete {
            get {
                return ResourceManager.GetString("Undelete", resourceCulture);
            }
        }
        
        public static string Unpin {
            get {
                return ResourceManager.GetString("Unpin", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        public static string NewPM {
            get {
                return ResourceManager.GetString("NewPM", resourceCulture);
            }
        }
        
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        public static string Unarchive {
            get {
                return ResourceManager.GetString("Unarchive", resourceCulture);
            }
        }
        
        public static string ViewArchivedMessages {
            get {
                return ResourceManager.GetString("ViewArchivedMessages", resourceCulture);
            }
        }
        
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string ErrorSettingUpDb {
            get {
                return ResourceManager.GetString("ErrorSettingUpDb", resourceCulture);
            }
        }
        
        public static string ForumReady {
            get {
                return ResourceManager.GetString("ForumReady", resourceCulture);
            }
        }
        
        public static string ForumTitle {
            get {
                return ResourceManager.GetString("ForumTitle", resourceCulture);
            }
        }
        
        public static string GoAdmin {
            get {
                return ResourceManager.GetString("GoAdmin", resourceCulture);
            }
        }
        
        public static string InvalidLink {
            get {
                return ResourceManager.GetString("InvalidLink", resourceCulture);
            }
        }
        
        public static string NoDataConnection {
            get {
                return ResourceManager.GetString("NoDataConnection", resourceCulture);
            }
        }
        
        public static string PopForumsSetup {
            get {
                return ResourceManager.GetString("PopForumsSetup", resourceCulture);
            }
        }
        
        public static string SetupCantConnect {
            get {
                return ResourceManager.GetString("SetupCantConnect", resourceCulture);
            }
        }
        
        public static string SetupConnSuccess {
            get {
                return ResourceManager.GetString("SetupConnSuccess", resourceCulture);
            }
        }
        
        public static string SetupDatabase {
            get {
                return ResourceManager.GetString("SetupDatabase", resourceCulture);
            }
        }
        
        public static string SetupFirstUser {
            get {
                return ResourceManager.GetString("SetupFirstUser", resourceCulture);
            }
        }
        
        public static string SubscribedTopics {
            get {
                return ResourceManager.GetString("SubscribedTopics", resourceCulture);
            }
        }
        
        public static string SubscribeLoggedIn {
            get {
                return ResourceManager.GetString("SubscribeLoggedIn", resourceCulture);
            }
        }
        
        public static string SubscribeNone {
            get {
                return ResourceManager.GetString("SubscribeNone", resourceCulture);
            }
        }
        
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        public static string UnsubscribeTopic {
            get {
                return ResourceManager.GetString("UnsubscribeTopic", resourceCulture);
            }
        }
        
        public static string ArchivedNewPosts {
            get {
                return ResourceManager.GetString("ArchivedNewPosts", resourceCulture);
            }
        }
        
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        public static string ClosedPinned {
            get {
                return ResourceManager.GetString("ClosedPinned", resourceCulture);
            }
        }
        
        public static string DeleteTopic {
            get {
                return ResourceManager.GetString("DeleteTopic", resourceCulture);
            }
        }
        
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        public static string ForgotPasswordEmail {
            get {
                return ResourceManager.GetString("ForgotPasswordEmail", resourceCulture);
            }
        }
        
        public static string ForgotPasswordSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordSubject", resourceCulture);
            }
        }
        
        public static string ForumNoPost {
            get {
                return ResourceManager.GetString("ForumNoPost", resourceCulture);
            }
        }
        
        public static string ForumNoView {
            get {
                return ResourceManager.GetString("ForumNoView", resourceCulture);
            }
        }
        
        public static string LessThanMinute {
            get {
                return ResourceManager.GetString("LessThanMinute", resourceCulture);
            }
        }
        
        public static string LoginToPost {
            get {
                return ResourceManager.GetString("LoginToPost", resourceCulture);
            }
        }
        
        public static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        public static string NewPosts {
            get {
                return ResourceManager.GetString("NewPosts", resourceCulture);
            }
        }
        
        public static string NewPostsClosed {
            get {
                return ResourceManager.GetString("NewPostsClosed", resourceCulture);
            }
        }
        
        public static string NewPostsClosedPinned {
            get {
                return ResourceManager.GetString("NewPostsClosedPinned", resourceCulture);
            }
        }
        
        public static string NewPostsPinned {
            get {
                return ResourceManager.GetString("NewPostsPinned", resourceCulture);
            }
        }
        
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        public static string NoNewPosts {
            get {
                return ResourceManager.GetString("NoNewPosts", resourceCulture);
            }
        }
        
        public static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        public static string OneMinuteAgo {
            get {
                return ResourceManager.GetString("OneMinuteAgo", resourceCulture);
            }
        }
        
        public static string Pinned {
            get {
                return ResourceManager.GetString("Pinned", resourceCulture);
            }
        }
        
        public static string PMCreateWarnings {
            get {
                return ResourceManager.GetString("PMCreateWarnings", resourceCulture);
            }
        }
        
        public static string PostEmpty {
            get {
                return ResourceManager.GetString("PostEmpty", resourceCulture);
            }
        }
        
        public static string PostWait {
            get {
                return ResourceManager.GetString("PostWait", resourceCulture);
            }
        }
        
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        public static string RegisterEmailSubject {
            get {
                return ResourceManager.GetString("RegisterEmailSubject", resourceCulture);
            }
        }
        
        public static string RegisterEmailThankYou {
            get {
                return ResourceManager.GetString("RegisterEmailThankYou", resourceCulture);
            }
        }
        
        public static string RegisterEmailThankYouVerify {
            get {
                return ResourceManager.GetString("RegisterEmailThankYouVerify", resourceCulture);
            }
        }
        
        public static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        public static string TodayTime {
            get {
                return ResourceManager.GetString("TodayTime", resourceCulture);
            }
        }
        
        public static string TopicNotExist {
            get {
                return ResourceManager.GetString("TopicNotExist", resourceCulture);
            }
        }
        
        public static string YesterdayTime {
            get {
                return ResourceManager.GetString("YesterdayTime", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string Voted {
            get {
                return ResourceManager.GetString("Voted", resourceCulture);
            }
        }
        
        public static string VoteUpPublishMessage {
            get {
                return ResourceManager.GetString("VoteUpPublishMessage", resourceCulture);
            }
        }
        
        public static string ScoringGame {
            get {
                return ResourceManager.GetString("ScoringGame", resourceCulture);
            }
        }
        
        public static string Awards {
            get {
                return ResourceManager.GetString("Awards", resourceCulture);
            }
        }
        
        public static string EventDefinitions {
            get {
                return ResourceManager.GetString("EventDefinitions", resourceCulture);
            }
        }
        
        public static string AwardDefinitions {
            get {
                return ResourceManager.GetString("AwardDefinitions", resourceCulture);
            }
        }
        
        public static string ManualEvent {
            get {
                return ResourceManager.GetString("ManualEvent", resourceCulture);
            }
        }
        
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        public static string ActivityFeed {
            get {
                return ResourceManager.GetString("ActivityFeed", resourceCulture);
            }
        }
        
        public static string NewReplyPublishMessage {
            get {
                return ResourceManager.GetString("NewReplyPublishMessage", resourceCulture);
            }
        }
        
        public static string NewPostPublishMessage {
            get {
                return ResourceManager.GetString("NewPostPublishMessage", resourceCulture);
            }
        }
        
        public static string ExternalLogins {
            get {
                return ResourceManager.GetString("ExternalLogins", resourceCulture);
            }
        }
        
        public static string UseExistingForumAccount {
            get {
                return ResourceManager.GetString("UseExistingForumAccount", resourceCulture);
            }
        }
        
        public static string ExpiredLogin {
            get {
                return ResourceManager.GetString("ExpiredLogin", resourceCulture);
            }
        }
        
        public static string ExternalLoginsDisabled {
            get {
                return ResourceManager.GetString("ExternalLoginsDisabled", resourceCulture);
            }
        }
        
        public static string NoExternalLoginsRegistered {
            get {
                return ResourceManager.GetString("NoExternalLoginsRegistered", resourceCulture);
            }
        }
        
        public static string DeletePermanently {
            get {
                return ResourceManager.GetString("DeletePermanently", resourceCulture);
            }
        }
        
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        public static string AskAQuestion {
            get {
                return ResourceManager.GetString("AskAQuestion", resourceCulture);
            }
        }
        
        public static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        public static string QuestionAnswered {
            get {
                return ResourceManager.GetString("QuestionAnswered", resourceCulture);
            }
        }
        
        public static string ChooseAnswer {
            get {
                return ResourceManager.GetString("ChooseAnswer", resourceCulture);
            }
        }
        
        public static string PostAnswer {
            get {
                return ResourceManager.GetString("PostAnswer", resourceCulture);
            }
        }
        
        public static string SubmitAnswer {
            get {
                return ResourceManager.GetString("SubmitAnswer", resourceCulture);
            }
        }
        
        public static string AppRestartRequired {
            get {
                return ResourceManager.GetString("AppRestartRequired", resourceCulture);
            }
        }
        
        public static string SearchError {
            get {
                return ResourceManager.GetString("SearchError", resourceCulture);
            }
        }
        
        public static string BotError {
            get {
                return ResourceManager.GetString("BotError", resourceCulture);
            }
        }
        
        public static string CloseOldTopics {
            get {
                return ResourceManager.GetString("CloseOldTopics", resourceCulture);
            }
        }
        
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        public static string PrivateForum {
            get {
                return ResourceManager.GetString("PrivateForum", resourceCulture);
            }
        }
        
        public static string AccountNotVerified {
            get {
                return ResourceManager.GetString("AccountNotVerified", resourceCulture);
            }
        }
        
        public static string SelectText {
            get {
                return ResourceManager.GetString("SelectText", resourceCulture);
            }
        }
        
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        public static string NewReplyNotification {
            get {
                return ResourceManager.GetString("NewReplyNotification", resourceCulture);
            }
        }
        
        public static string Award {
            get {
                return ResourceManager.GetString("Award", resourceCulture);
            }
        }
        
        public static string VoteUpNotification {
            get {
                return ResourceManager.GetString("VoteUpNotification", resourceCulture);
            }
        }
        
        public static string QuestionAnsweredNotification {
            get {
                return ResourceManager.GetString("QuestionAnsweredNotification", resourceCulture);
            }
        }
        
        public static string AutoFollow {
            get {
                return ResourceManager.GetString("AutoFollow", resourceCulture);
            }
        }
        
        public static string MarkAllRead {
            get {
                return ResourceManager.GetString("MarkAllRead", resourceCulture);
            }
        }
        
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        public static string Ignored {
            get {
                return ResourceManager.GetString("Ignored", resourceCulture);
            }
        }
        
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        public static string IgnoreList {
            get {
                return ResourceManager.GetString("IgnoreList", resourceCulture);
            }
        }
    }
}
