using System;
using System.Globalization;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Configuration;
using PopForums.Extensions;
using PopForums.Sql;
using PopForums.AzureKit;
using PopForums.AzureKit.Functions;
using PopForums.ElasticKit;

var configuration = new ConfigurationBuilder()
	.SetBasePath(Environment.CurrentDirectory)
	.AddJsonFile("local.settings.json", true)
	.AddJsonFile("local.settings.dev.json", true)
	.AddEnvironmentVariables()
	.Build();

// set the language for notifications generated by functions (otherwise it's whatever Azure
// defaults to, probably en-US), applies to every thread in the process
//CultureInfo.DefaultThreadCurrentCulture = CultureInfo.GetCultureInfo("es");
//CultureInfo.DefaultThreadCurrentUICulture = CultureInfo.GetCultureInfo("es");

var host = new HostBuilder()
	.UseDefaultServiceProvider((_, options) =>
	{
		// there are types not used in functions in core library, so don't choke on them
		options.ValidateOnBuild = false;
	})
	.ConfigureFunctionsWorkerDefaults()
	.ConfigureAppConfiguration(c =>
	{
		c.AddConfiguration(configuration);
	})
	.ConfigureServices(s =>
	{
		// set up the dependencies for the SQL library in POP Forums
		s.AddPopForumsBase();
		s.AddPopForumsSql();

		// route background work to Azure queues, and wire up the broker/cache/notification
		// tunnel needed to talk back to the web front end (which is specified in the
		// PopForums:WebAppUrlAndArea value)
		s.AddPopForumsAzureFunctionsAndQueues();
		s.AddPopForumsFunctionsHost();

		// persist image uploads to Azure blob storage, see configuration
		s.AddPopForumsAzureBlobStorageForPostImages();

		// use Azure table storage for logging instead of database
		//s.AddPopForumsTableStorageLogging();

		// use Azure Search for POP Forums using AzureKit (match the web app)
		//s.AddPopForumsAzureSearch();

		// use ElasticSearch for POP Forums using ElasticKit (match the web app)
		//s.AddPopForumsElasticSearch();
	})
	.Build();

await host.RunAsync();
